//! The manual, as a table the programs can read at compile time.
//!
//! Every command's one-line summary exists twice: in the manual page a
//! person reads, and in the listing `tools` and `help` print. Written
//! twice they drift, and they did: half of them disagreed, and one pair
//! contradicted outright. So the page is the source, this reads its
//! title line, and the programs take their summaries from here.
//!
//! Run by the build with the manual directory and an output path. Emits
//! Zig rather than text, because what wants the answer is a comptime
//! table lookup that fails the build when a command has no page.

const std = @import("std");

pub fn main(init: std.process.Init) !void {
    const arena = init.arena.allocator();
    const io = init.io;
    const args = try init.minimal.args.toSlice(arena);
    if (args.len < 2) {
        std.debug.print("usage: gen-manual-index <out.zig> <page>...\n", .{});
        std.process.exit(2);
    }
    const out_path = args[1];

    // Every page arrives as its own argument rather than as a directory
    // to walk: the build system hashes what it is handed, so a page that
    // changed, arrived or left is one the build notices.
    var paths: std.ArrayList([]const u8) = .empty;
    for (args[2..]) |path| try paths.append(arena, path);

    // Sorted by the name a command is looked up under, so the generated
    // table is the same every time and an unchanged manual produces an
    // unchanged file.
    std.mem.sort([]const u8, paths.items, {}, lessThan);

    var text: std.ArrayList(u8) = .empty;

    try text.appendSlice(arena,
        \\//! The manual's own titles, for the programs that list commands.
        \\//!
        \\//! Generated by tools/gen-manual-index.zig from the manual
        \\//! directory. The page is the source: edit `manual/<name>`, and
        \\//! what `tools` and `help` print follows.
        \\
        \\
        \\pub const Page = struct {
        \\    name: []const u8,
        \\    summary: []const u8,
        \\};
        \\
        \\pub const pages = [_]Page{
        \\
    );

    for (paths.items) |path| {
        const name = std.fs.path.basename(path);
        const summary = try titleOf(io, arena, path, name);
        try text.print(arena, "    .{{ .name = \"{s}\", .summary = \"{s}\" }},\n", .{ name, summary });
    }

    try text.appendSlice(arena,
        \\};
        \\
        \\/// The summary of the page named, or a build failure saying which
        \\/// command has no page. A command nobody documented is a command
        \\/// nobody can look up, which is worth refusing to ship.
        \\pub fn summaryOf(comptime name: []const u8) []const u8 {
        \\    comptime {
        \\        // Every command walks the whole table once; the default
        \\        // quota is sized for fewer commands than a system has.
        \\        @setEvalBranchQuota(pages.len * 200);
        \\        for (pages) |page| {
        \\            if (std.mem.eql(u8, page.name, name)) return page.summary;
        \\        }
        \\        @compileError("no manual page for the command '" ++ name ++ "'; write manual/" ++ name);
        \\    }
        \\}
        \\
        \\const std = @import("std");
        \\
    );

    try std.Io.Dir.cwd().writeFile(io, .{ .sub_path = out_path, .data = text.items });
}

fn lessThan(_: void, a: []const u8, b: []const u8) bool {
    return std.mem.lessThan(u8, std.fs.path.basename(a), std.fs.path.basename(b));
}

/// A page's title line is `name - summary`; the summary is what follows
/// the dash. A page whose first line is not that shape is a page written
/// wrong, and the build says so rather than emitting something odd.
fn titleOf(io: std.Io, arena: std.mem.Allocator, path: []const u8, name: []const u8) ![]const u8 {
    const contents = try std.Io.Dir.cwd().readFileAlloc(io, path, arena, .limited(64 * 1024));
    const first = std.mem.sliceTo(contents, '\n');

    const separator = " - ";
    const at = std.mem.indexOf(u8, first, separator) orelse {
        std.debug.print("manual/{s}: first line is not 'name - summary'\n", .{name});
        std.process.exit(1);
    };
    if (!std.mem.eql(u8, first[0..at], name)) {
        std.debug.print(
            "manual/{s}: titled '{s}', which is not the page's own name\n",
            .{ name, first[0..at] },
        );
        std.process.exit(1);
    }
    return first[at + separator.len ..];
}
